### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### Tarefas Concluidas
GET http://localhost:5000/tarefas/concluidas
Content-Type: application/json

{
    "id": 4,
    "titulo": "Enviar relatório final",
    "status": "Concluída"
}
  
### Tarefas Nao concluidas
GET http://localhost:5000/tarefas/naoconcluidas
Content-Type: application/json

{
    "id": 1,
    "titulo": "Organizar documentos",
    "status": "Não iniciada"
  },
  {
    "id": 3,
    "titulo": "Atualizar projeto",
    "status": "Em andamento"
  }

###Alterar tarefa
PUT http://localhost:5000/tarefas/alterar/