### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### Tarefas Concluidas
GET http://localhost:5000/tarefas/concluidas


### Tarefas Nao concluidas
GET http://localhost:5000/tarefas/naoconcluidas